pipeline {
  agent any

  parameters {
    string(name: 'SERVICE_NAME', defaultValue: 'api-gateway', description: 'Name of the microservice')
    string(name: 'IMAGE_TAG', defaultValue: '', description: 'Leave empty to use BUILD_NUMBER')
    string(name: 'DOCKERHUB_REPO', defaultValue: 'innabelle1/spring-petclinic-api-gateway', description: 'DockerHub repo name')
  }

  environment {
    AWS_REGION      = 'us-east-1'
    ECR_REGISTRY    = '701173654142.dkr.ecr.us-east-1.amazonaws.com'
    ECR_REPO        = "${ECR_REGISTRY}/petclinic/${params.SERVICE_NAME}"
    IMAGE_TAG       = "${params.IMAGE_TAG ?: env.BUILD_NUMBER}"
    DOCKERHUB_REPO  = "${params.DOCKERHUB_REPO}"
  }

  stages {

    stage('Login to DockerHub & ECR') {
      steps {
        script {
          sh "echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin"
          sh "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY"
        }
      }
    }

    stage('Pull from DockerHub') {
      steps {
        script {
          sh "docker pull $DOCKERHUB_REPO:$IMAGE_TAG"
        }
      }
    }

    stage('Tag for ECR') {
      steps {
        script {
          sh "docker tag $DOCKERHUB_REPO:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG"
        }
      }
    }

    stage('Push to ECR') {
      steps {
        script {
          sh "docker push $ECR_REPO:$IMAGE_TAG"
        }
      }
    }

    stage('Verify ECR Image') {
      steps {
        script {
          def check = sh(
            script: """aws ecr describe-images \
              --repository-name petclinic/${params.SERVICE_NAME} \
              --image-ids imageTag=$IMAGE_TAG \
              --region $AWS_REGION > /dev/null 2>&1""",
            returnStatus: true
          )
          if (check != 0) {
            error("ECR image not found: petclinic/${params.SERVICE_NAME}:$IMAGE_TAG")
          } else {
            echo "ECR image verified: petclinic/${params.SERVICE_NAME}:$IMAGE_TAG"
          }
        }
      }
    }
  }

  post {
    failure {
      echo "Failed to sync image for ${params.SERVICE_NAME}"
    }
    success {
      echo "Image ${params.SERVICE_NAME}:$IMAGE_TAG successfully pushed to ECR"
    }
  }
}
